version: "3.9"
services:
  nginx:
    container_name: nginx-server
    ports:
      - "80:80"
  f1-news:
    build:
      context: ./f1-news
      args:
        NODE_ENV: development
    environment:
      - NODE_ENV=development
    # Specify an array of ports to map
    ports:
      - '3008:3000'
    command: npm run dev
    # env_file:
    #   - ./.env